/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import LibraryFunctions.respository;
import LibraryFunctions.MenuHelper;
import Objects.Ticket;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author fv200399
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        TechnicianNameLabel.setText(respository.getCurrentUser().getName());
        AdminMessage.setVisible(false);
        OpenTicketList.setModel(MenuHelper.openTickets());
        ClosedTicketsList.setModel(MenuHelper.recentlyClosedTickets());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogOffBtn = new javax.swing.JButton();
        OpenTickets = new javax.swing.JScrollPane();
        OpenTicketList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ClosedTickets = new javax.swing.JScrollPane();
        ClosedTicketsList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        TechnicianNameLabel = new javax.swing.JLabel();
        openTicketBtn = new javax.swing.JButton();
        addCustomerBtn = new javax.swing.JButton();
        findTicketBtn = new javax.swing.JButton();
        addTechnicianBtn = new javax.swing.JButton();
        findCustomerBtn = new javax.swing.JButton();
        AddDeviceBtn = new javax.swing.JButton();
        AddNoteBtn = new javax.swing.JButton();
        FindDeviceBtn = new javax.swing.JButton();
        FindNotesBtn = new javax.swing.JButton();
        AdminMessage = new javax.swing.JLabel();
        EditCustomerBtn = new javax.swing.JButton();
        EditTicketBtn = new javax.swing.JButton();
        EditDeviceBtn = new javax.swing.JButton();
        EditNotesBtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LogOffBtn.setText("Log Off");
        LogOffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOffBtnActionPerformed(evt);
            }
        });

        OpenTicketList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        OpenTickets.setViewportView(OpenTicketList);

        jLabel1.setText("Open Tickets");

        jLabel2.setText("Recently Closed Tickets");

        ClosedTicketsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ClosedTickets.setViewportView(ClosedTicketsList);

        jLabel3.setText("Technician: ");

        TechnicianNameLabel.setText("Technician Name");

        openTicketBtn.setText("Open Ticket");
        openTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTicketBtnActionPerformed(evt);
            }
        });

        addCustomerBtn.setText("Add Customer");
        addCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBtnActionPerformed(evt);
            }
        });

        findTicketBtn.setText("Find Ticket");
        findTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findTicketBtnActionPerformed(evt);
            }
        });

        addTechnicianBtn.setText("Add Technician");
        addTechnicianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTechnicianBtnActionPerformed(evt);
            }
        });

        findCustomerBtn.setText("Find Customer");
        findCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findCustomerBtnActionPerformed(evt);
            }
        });

        AddDeviceBtn.setText("Add Device");
        AddDeviceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDeviceBtnActionPerformed(evt);
            }
        });

        AddNoteBtn.setText("Add Notes");
        AddNoteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNoteBtnActionPerformed(evt);
            }
        });

        FindDeviceBtn.setText("Find Device");
        FindDeviceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindDeviceBtnActionPerformed(evt);
            }
        });

        FindNotesBtn.setText("Find Notes");
        FindNotesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindNotesBtnActionPerformed(evt);
            }
        });

        AdminMessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AdminMessage.setForeground(new java.awt.Color(255, 0, 0));
        AdminMessage.setText("Must have admin privelleges");

        EditCustomerBtn.setText("EditCustomer");
        EditCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditCustomerBtnActionPerformed(evt);
            }
        });

        EditTicketBtn.setText("Edit Ticket");
        EditTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTicketBtnActionPerformed(evt);
            }
        });

        EditDeviceBtn.setText("Edit Device");
        EditDeviceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditDeviceBtnActionPerformed(evt);
            }
        });

        EditNotesBtn.setText("Edit Notes");
        EditNotesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditNotesBtnActionPerformed(evt);
            }
        });

        jButton6.setText("Edit Technician");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(TechnicianNameLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(OpenTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ClosedTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(AdminMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addTechnicianBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(openTicketBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(addCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(AddDeviceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddNoteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 148, Short.MAX_VALUE)
                                .addComponent(LogOffBtn)
                                .addContainerGap(84, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FindDeviceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(findTicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(findCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FindNotesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EditNotesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EditDeviceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EditTicketBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EditCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(38, 38, 38))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TechnicianNameLabel)
                    .addComponent(LogOffBtn))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OpenTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addCustomerBtn)
                                    .addComponent(EditCustomerBtn)
                                    .addComponent(findCustomerBtn))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(openTicketBtn)
                                    .addComponent(EditTicketBtn)
                                    .addComponent(findTicketBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddDeviceBtn)
                                    .addComponent(FindDeviceBtn)
                                    .addComponent(EditDeviceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddNoteBtn)
                                    .addComponent(EditNotesBtn)
                                    .addComponent(FindNotesBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addTechnicianBtn)
                                    .addComponent(jButton6))))
                        .addGap(4, 4, 4)
                        .addComponent(ClosedTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AdminMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTicketBtnActionPerformed
        OpenTicket open = new OpenTicket();
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_openTicketBtnActionPerformed

    private void findTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findTicketBtnActionPerformed
        FindTicket findTicket = new FindTicket();
        findTicket.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_findTicketBtnActionPerformed

    private void addTechnicianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTechnicianBtnActionPerformed
    if(respository.getCurrentUser().isAdmin()){
        AddTechnician addTech = new AddTechnician();
        addTech.setVisible(true);
        this.dispose();
    }
    else{
        AdminMessage.setVisible(true);
    }
    }//GEN-LAST:event_addTechnicianBtnActionPerformed

    private void addCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBtnActionPerformed
        AddCustomer addCust = new AddCustomer();
        addCust.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addCustomerBtnActionPerformed

    private void LogOffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOffBtnActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOffBtnActionPerformed

    private void findCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findCustomerBtnActionPerformed
        FindCustomer FindCust = new FindCustomer();
        FindCust.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_findCustomerBtnActionPerformed

    private void AddNoteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNoteBtnActionPerformed
        AddNotes addnotes = new AddNotes();
        addnotes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddNoteBtnActionPerformed

    private void FindDeviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindDeviceBtnActionPerformed
        FindDevice FindDev = new FindDevice();
        FindDev.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FindDeviceBtnActionPerformed

    private void AddDeviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDeviceBtnActionPerformed
        AddDevice addDev = new AddDevice();
        addDev.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddDeviceBtnActionPerformed

    private void FindNotesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindNotesBtnActionPerformed
        FindNotes FindNotes = new FindNotes();
        FindNotes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FindNotesBtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    if(respository.getCurrentUser().isAdmin()){
        EditTechnician EditTech = new EditTechnician();
        EditTech.setVisible(true);
        this.dispose();
    }
    else{
        AdminMessage.setVisible(true);
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void EditCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditCustomerBtnActionPerformed
        EditCustomer EditCust = new EditCustomer();
        EditCust.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditCustomerBtnActionPerformed

    private void EditTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTicketBtnActionPerformed
        EditTickets EditTicket = new EditTickets();
        EditTicket.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditTicketBtnActionPerformed

    private void EditDeviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDeviceBtnActionPerformed
        EditDevice EditDevice = new EditDevice();
        EditDevice.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditDeviceBtnActionPerformed

    private void EditNotesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditNotesBtnActionPerformed
        EditNotes EditNotes = new EditNotes();
        EditNotes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditNotesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDeviceBtn;
    private javax.swing.JButton AddNoteBtn;
    private javax.swing.JLabel AdminMessage;
    private javax.swing.JScrollPane ClosedTickets;
    private javax.swing.JList<String> ClosedTicketsList;
    private javax.swing.JButton EditCustomerBtn;
    private javax.swing.JButton EditDeviceBtn;
    private javax.swing.JButton EditNotesBtn;
    private javax.swing.JButton EditTicketBtn;
    private javax.swing.JButton FindDeviceBtn;
    private javax.swing.JButton FindNotesBtn;
    private javax.swing.JButton LogOffBtn;
    private javax.swing.JList<String> OpenTicketList;
    private javax.swing.JScrollPane OpenTickets;
    private javax.swing.JLabel TechnicianNameLabel;
    private javax.swing.JButton addCustomerBtn;
    private javax.swing.JButton addTechnicianBtn;
    private javax.swing.JButton findCustomerBtn;
    private javax.swing.JButton findTicketBtn;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton openTicketBtn;
    // End of variables declaration//GEN-END:variables
}
